# IMPORTANT: This file is generated by `rails generate cucumber:install`
# It sets up the environment for Cucumber to run in your Rails app

ENV["RAILS_ENV"] ||= "test"

require File.expand_path("../../config/environment", __dir__)
require "cucumber/rails"
require "capybara/rails"
require "capybara/cucumber"
require "selenium-webdriver"

# Use the database cleaner strategy to avoid stale test data
begin
  DatabaseCleaner.strategy = :transaction
rescue NameError
  raise "Add `database_cleaner` to your Gemfile (in the test group) to use it."
end

# Use truncation for JavaScript scenarios
Cucumber::Rails::Database.javascript_strategy = :truncation

# Capybara settings
Capybara.default_max_wait_time = 5

# ✅ Use headless Chrome for JavaScript tests
Capybara.default_driver = :selenium_chrome_headless
Capybara.javascript_driver = :selenium_chrome_headless

# ✅ Set your app host if you're running via port-forwarded dev envs
Capybara.app_host = 'http://localhost:3000'
Capybara.server_port = 3000
