default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: my_db_wjmy_user # <-- Replace with your actual DB username from Render
  password: <%= ENV['DATABASE_PASSWORD'] %> # leave this as-is
  url: <%= ENV['DATABASE_URL'] %> # leave this as-is

development:
  <<: *default
  database: my_db_wjmy # optional override

test:
  <<: *default
  database: my_db_wjmy_test # optional override

production:
  <<: *default
  database: my_db_wjmy # <-- Replace with your actual DB name from Render
